mail:
  username: "numax8425@gmail.com"
  server: "smtp.gmail.com"
  port: 465
  ssl: true
  from: "numax8425@gmail.com"
  password: "eamil_password"
  to: [
    "wayne011872@gmail.com",
  ]
line:
    notifyUrl: "https://notify.numax.com.tw/v1/notify"
    token: "notify_token"
mongo:
    uri: mongodb://localhost:27017
    defaul: systemMonitor
