mail:
  username: "numax84257736@gmail.com"
  server: "smtp.gmail.com"
  port: "465"
  ssl: true
  from: "numax84257736@gmail.com"
  password: "eakkxyfymdmzgaul"
  to: [
    "wayne011872@gmail.com",
  ]
mongo:
    uri: mongodb://localhost:27017
    defaul: systemMonitor
log:
    level: debug
    target: os